CLOUD-538 Script created for update a nuget package
Aqovia/dev-scripts pull request #1
Opened 2018-07-02 14:46 UTC by sedainterxion

Script created for update a nuget package in a working directory which should be parent directory of all repos

2018-07-02 15:46 UTC, margani approved these changes

2018-07-03 13:11 UTC, ma499 requested changes
Looks fine. But can we implement Component-Based help by adding documentation in the correct comment format? See https://technet.microsoft.com/en-us/library/ff458353.aspx

2018-07-03 13:11 UTC, ma499 commented on aqovia-nuget-update.ps1
> +$xunitConsoleExe = $workingDir+"\xunit.runner.console.*\tools\net452\xunit.console.x86.exe"
If time, maybe search for the exe / frameworkversion rather than assuming net452

2018-07-04 11:31 UTC, ma499 approved these changes

2018-07-04 15:30 UTC, merged